const char html[] PROGMEM = "<!DOCTYPE html><html"
                            " lang=\"en\"><head> "
                            "<meta charset=\"UTF-"
                            "8\"> <meta name=\"vi"
                            "ewport\" content=\"w"
                            "idth=device-width, i"
                            "nitial-scale=1\"> <t"
                            "itle>Robo Car Contro"
                            "ller v2.0</title> <l"
                            "ink href=\"data:imag"
                            "e/png;base64,iVBORw0"
                            "KGgoAAAANSUhEUgAAABA"
                            "AAAAQCAYAAAAf8/9hAAA"
                            "AAXNSR0IArs4c6QAAApF"
                            "JREFUOE+VkV9IU3EUx7+"
                            "/u3t376Zzm8vp/FNUBGY"
                            "khik5i4gUK3spKYhAeui"
                            "lhAZKQfYH6Y/SH4tV1ks"
                            "PYX8eDOslK7OoEDMsMQx"
                            "KiIpyOt1SN+e2u91/4R2"
                            "ayh7y93TO+Z3z4fA5BAu"
                            "e0lu+Wo5K1dLEny1KJLp"
                            "0+puw2t8a85LXlFZzheS"
                            "3fZ07QmaSlMNNiUaRvrh"
                            "12egBKjihU6L8PDTRcpA"
                            "TzOFXv1Lv+GnxmPdm1ZQ"
                            "Kn+na3NhzPODz1i/cKF5"
                            "uMKXUvq0pbJgF7Gnx5IG"
                            "i+/5neLZHFtc93Gv9RKZ"
                            "actJcVP7gKThphgJKV7D"
                            "QMwQvf0bg4xW138QRlCx"
                            "nERIUdPyIQJCBs3CImXJ"
                            "vFgneSH7hSttRehLXcCh"
                            "fj9zHzRDdHkSqHTjaJai"
                            "AS3YG7FUnaJsV/bsqcas"
                            "3hHM4gsyRpx0keN0Uddl"
                            "2MtMAZ7EG4bIKdSitqR4"
                            "O3yo1dpq+YaSqVo117a1"
                            "wdEkxgPuJQEJN5nuDqeX"
                            "7pwGVuTps+vAM4ogH3n2"
                            "VOP0udokzdhYpD+6qG3Q"
                            "WbEdzf1gFZI223SdKy5r"
                            "kL6Twcx1pTCcEKExnVAf"
                            "dLgG8GHPA0QRFmYzqoGd"
                            "YgKIAdUrNcI7Ss1Y94+7"
                            "WsQ0ahXQv5goSUYoeVVj"
                            "ezwOsT46gLNuEsQk/DIl"
                            "6RKIxiayWQWAqBIvZiPY"
                            "BHz6Os4gLOLhyEsXZNgx"
                            "5xmAxGhDiozFxnBbj/gA"
                            "yrBZ0Dbhx+3tSfICVk5B"
                            "n4xAM8+C0DERJUgG0RgM"
                            "+KiBBx6HPzcPLa/4B7A1"
                            "vCmiGPc9w+tK5DnQJSdA"
                            "ZjGopHPAjHJycp0jgQx2"
                            "iEDlB7Bc6LxMFNfEEmqw"
                            "ZatnnGYrrVyFoJBsbOkt"
                            "kCtsWc4GZXkrG87/heA2"
                            "fguteGQAAAABJRU5ErkJ"
                            "ggg\" rel=\"icon\" t"
                            "ype=\"image/x-icon\""
                            "/> <script src=\"htt"
                            "ps://code.jquery.com"
                            "/jquery-3.6.0.min.js"
                            "\" crossorigin=\"ano"
                            "nymous\"></script> <"
                            "script>var keydowned"
                            "=false; $(document)."
                            "ready(function (){$("
                            "\".key\").on(\"mouse"
                            "down touchstart\", f"
                            "unction (){console.l"
                            "og(\"mouse down\"); "
                            "ajaxCall(\"\" + $(th"
                            "is).attr(\"data-key"
                            "\"));}); $(\".key\")"
                            ".on(\"mouseup touche"
                            "nd\", function (){co"
                            "nsole.log(\"mouse up"
                            "\"); ajaxCall(999);}"
                            "); $(document).keydo"
                            "wn(function (event){"
                            "if (!keydowned){keyd"
                            "owned=true; console."
                            "log(\"keydown=\" + e"
                            "vent.which); ajaxCal"
                            "l(\"\" + event.which"
                            "); $(`[data-key=${ev"
                            "ent.which}]`).addCla"
                            "ss(\"active\");}}); "
                            "$(document).keyup(fu"
                            "nction (){console.lo"
                            "g(\"keyup\"); keydow"
                            "ned=false; ajaxCall("
                            "999); $(`[data-key=$"
                            "{event.which}]`).rem"
                            "oveClass(\"active\")"
                            ";});}); function aja"
                            "xCall(action){let a;"
                            " switch (action){cas"
                            "e \"37\": case 37: a"
                            "=\"left\"; break; ca"
                            "se \"38\": case 38: "
                            "a=\"fwd\"; break; ca"
                            "se \"39\": case 39: "
                            "a=\"right\"; break; "
                            "case \"40\": case 40"
                            ": a=\"bkw\"; break; "
                            "case \"999\": case 9"
                            "99: a=\"stop\"; brea"
                            "k; default: return;}"
                            "var uri=\"/action/?a"
                            "=\" + a; $.ajax({url"
                            ": uri, error: functi"
                            "on (xmlhttprequest, "
                            "textstatus, message)"
                            "{if (textstatus===\""
                            "timeout\"){$(\".stat"
                            "us\").html(`Couldn\'"
                            "t connect to RoboCar"
                            ": ${textstatus}`).ad"
                            "dClass(\"error\")}el"
                            "se{if (message){$(\""
                            ".status\").html(`ERR"
                            "OR: ${message}`).add"
                            "Class(\"error\");}el"
                            "se{$(\".status\").ht"
                            "ml(`ERROR: ${textsta"
                            "tus}`).addClass(\"er"
                            "ror\");}}}, success:"
                            " function (resp){if "
                            "(resp?.message){if ("
                            "resp.message==\"obst"
                            "acle ahead\"){$(\".s"
                            "tatus\").html(resp.m"
                            "essage).addClass(\"e"
                            "rror\"); $(\".key.up"
                            "\").addClass(\"obsta"
                            "cle\");}else{$(\".st"
                            "atus\").html(resp.me"
                            "ssage).removeClass("
                            "\"error\"); $(\".key"
                            ".up\").removeClass("
                            "\"obstacle\");}}else"
                            "{$(\".status\").html"
                            "(`Connected`).remove"
                            "Class(\"error\");}},"
                            " timeout: 3000});}</"
                            "script> <style>body{"
                            "font-family: Arial, "
                            "Helvetica, sans-seri"
                            "f;}.btn{color: #ffff"
                            "ff; font-size: 20px;"
                            " background: #3498db"
                            "; padding: 10px 20px"
                            " 10px 20px; text-dec"
                            "oration: none; box-s"
                            "hadow: 10px 10px 10p"
                            "x rgba(0, 0, 0, 0.5)"
                            "; border: none;}.btn"
                            ":hover{background: #"
                            "3cb0fd; text-decorat"
                            "ion: none;}.btn-wrp{"
                            "height: 400px; width"
                            ": 400px; position: f"
                            "ixed; left: 50%; bot"
                            "tom: 0; transform: t"
                            "ranslate(-50%, 30%);"
                            "}.btn:active, .activ"
                            "e{transform: scale(0"
                            ".9); background-colo"
                            "r: #34db9b; border: "
                            "none;}.key{position:"
                            " absolute; height: 4"
                            "8px; width: 108px;}."
                            "key.up{top: 50px; le"
                            "ft: 150px;}.key.down"
                            "{top: 170px; left: 1"
                            "50px;}.key.left{top:"
                            " 170px; left: 0px;}."
                            "key.right{top: 170px"
                            "; right: 0px;}.statu"
                            "s{position: fixed; t"
                            "op: 30px; right: 10p"
                            "x; font-size: 20px; "
                            "color: green;}.error"
                            "{color: red;}.obstac"
                            "le{background-color:"
                            " red;}iframe{height:"
                            " calc(100vh - 100px)"
                            "; width: calc(100vw "
                            "- 20px); border: 0;}"
                            "</style></head><body"
                            "> <h1>Robo Car Contr"
                            "oller v2.0</h1> <ifr"
                            "ame src=\"http://192"
                            ".168.0.112/picture/1"
                            "/frame/\"></iframe> "
                            "<div class=\"status"
                            "\"> </div><div class"
                            "=\"btn-wrp\"> <butto"
                            "n type=\"button\" cl"
                            "ass=\"btn key up\" d"
                            "ata-key=\"38\">&uarr"
                            ";</button> <button t"
                            "ype=\"button\" class"
                            "=\"btn key left\" da"
                            "ta-key=\"37\">&larr;"
                            "</button> <button ty"
                            "pe=\"button\" class="
                            "\"btn key right\" da"
                            "ta-key=\"39\">&rarr;"
                            "</button> <button ty"
                            "pe=\"button\" class="
                            "\"btn key down\" dat"
                            "a-key=\"40\">&darr;<"
                            "/button> </div></bod"
                            "y></html>";