const char html[] PROGMEM  = "<!DOCTYPE html><html"
   " lang=\"en\"><head> "
   "<meta charset=\"UTF-"
   "8\"> <meta name=\"vi"
   "ewport\" content=\"w"
   "idth=device-width, i"
   "nitial-scale=1\"> <t"
   "itle>Robo Car Contro"
   "ller v2.0</title> <l"
   "ink href=\"data:imag"
   "e/png;base64,iVBORw0"
   "KGgoAAAANSUhEUgAAABA"
   "AAAAQCAYAAAAf8/9hAAA"
   "AAXNSR0IArs4c6QAAApF"
   "JREFUOE+VkV9IU3EUx7+"
   "/u3t376Zzm8vp/FNUBGY"
   "khik5i4gUK3spKYhAeui"
   "lhAZKQfYH6Y/SH4tV1ks"
   "PYX8eDOslK7OoEDMsMQx"
   "KiIpyOt1SN+e2u91/4R2"
   "ayh7y93TO+Z3z4fA5BAu"
   "e0lu+Wo5K1dLEny1KJLp"
   "0+puw2t8a85LXlFZzheS"
   "3fZ07QmaSlMNNiUaRvrh"
   "12egBKjihU6L8PDTRcpA"
   "TzOFXv1Lv+GnxmPdm1ZQ"
   "Kn+na3NhzPODz1i/cKF5"
   "uMKXUvq0pbJgF7Gnx5IG"
   "i+/5neLZHFtc93Gv9RKZ"
   "actJcVP7gKThphgJKV7D"
   "QMwQvf0bg4xW138QRlCx"
   "nERIUdPyIQJCBs3CImXJ"
   "vFgneSH7hSttRehLXcCh"
   "fj9zHzRDdHkSqHTjaJai"
   "AS3YG7FUnaJsV/bsqcas"
   "3hHM4gsyRpx0keN0Uddl"
   "2MtMAZ7EG4bIKdSitqR4"
   "O3yo1dpq+YaSqVo117a1"
   "wdEkxgPuJQEJN5nuDqeX"
   "7pwGVuTps+vAM4ogH3n2"
   "VOP0udokzdhYpD+6qG3Q"
   "WbEdzf1gFZI223SdKy5r"
   "kL6Twcx1pTCcEKExnVAf"
   "dLgG8GHPA0QRFmYzqoGd"
   "YgKIAdUrNcI7Ss1Y94+7"
   "WsQ0ahXQv5goSUYoeVVj"
   "ezwOsT46gLNuEsQk/DIl"
   "6RKIxiayWQWAqBIvZiPY"
   "BHz6Os4gLOLhyEsXZNgx"
   "5xmAxGhDiozFxnBbj/gA"
   "yrBZ0Dbhx+3tSfICVk5B"
   "n4xAM8+C0DERJUgG0RgM"
   "+KiBBx6HPzcPLa/4B7A1"
   "vCmiGPc9w+tK5DnQJSdA"
   "ZjGopHPAjHJycp0jgQx2"
   "iEDlB7Bc6LxMFNfEEmqw"
   "ZatnnGYrrVyFoJBsbOkt"
   "kCtsWc4GZXkrG87/heA2"
   "fguteGQAAAABJRU5ErkJ"
   "ggg\" rel=\"icon\" t"
   "ype=\"image/x-icon\""
   "/> <script src=\"htt"
   "ps://code.jquery.com"
   "/jquery-3.6.0.min.js"
   "\" crossorigin=\"ano"
   "nymous\"></script> <"
   "script>var keydowned"
   "=false; $(document)."
   "ready(function (){$("
   "\".key\").mousedown("
   "function (){console."
   "log(\"mouse down\");"
   " restCall(\"\" + $(t"
   "his).attr(\"data-key"
   "\"));}); $(\".key\")"
   ".mouseup(function ()"
   "{console.log(\"mouse"
   " up\"); restCall(999"
   ");}); $(document).ke"
   "ydown(function (even"
   "t){if (!keydowned){k"
   "eydowned=true; conso"
   "le.log(\"keydown=\" "
   "+ event.which); rest"
   "Call(\"\" + event.wh"
   "ich); $(`[data-key=$"
   "{event.which}]`).add"
   "Class(\"active\");}}"
   "); $(document).keyup"
   "(function (){console"
   ".log(\"keyup\"); key"
   "downed=false; restCa"
   "ll(999); $(`[data-ke"
   "y=${event.which}]`)."
   "removeClass(\"active"
   "\");});}); function "
   "restCall(action){swi"
   "tch (action){case \""
   "37\": case 37: a=\"l"
   "eft\"; break; case "
   "\"38\": case 38: a="
   "\"fwd\"; break; case"
   " \"39\": case 39: a="
   "\"right\"; break; ca"
   "se \"40\": case 40: "
   "a=\"bkw\"; break; ca"
   "se \"999\": case 999"
   ": a=\"stop\"; break;"
   " default: return;}va"
   "r uri=\"/action/?a="
   "\" + a; $.ajax({url:"
   " uri, error: functio"
   "n (xmlhttprequest, t"
   "extstatus, message){"
   "if (textstatus===\"t"
   "imeout\"){$(\".statu"
   "s\").html(`Couldn\'t"
   " connect to RoboCar:"
   " ${textstatus}`).add"
   "Class(\"error\")}els"
   "e{$(\".status\").htm"
   "l(`ERROR: ${textstat"
   "us}${message}`).addC"
   "lass(\"error\")}}, s"
   "uccess: function (re"
   "sp){if (resp?.messag"
   "e){$(\".status\").ht"
   "ml(resp.message).rem"
   "oveClass(\"error\")}"
   "else{$(\".status\")."
   "html(`Connected`).re"
   "moveClass(\"error\")"
   "}}, timeout: 3000});"
   "}</script> <style>bo"
   "dy{font-family: Aria"
   "l, Helvetica, sans-s"
   "erif;}.btn{color: #f"
   "fffff; font-size: 20"
   "px; background: #349"
   "8db; padding: 10px 2"
   "0px 10px 20px; text-"
   "decoration: none; bo"
   "x-shadow: 10px 10px "
   "10px rgba(0, 0, 0, 0"
   ".5); border: none;}."
   "btn:hover{background"
   ": #3cb0fd; text-deco"
   "ration: none;}.btn-w"
   "rp{height: 400px; wi"
   "dth: 400px; position"
   ": absolute; left: 50"
   "%; top: 70%; transfo"
   "rm: translate(-50%, "
   "-50%);}.btn:active, "
   ".active{transform: s"
   "cale(0.9); backgroun"
   "d-color: #34db9b; bo"
   "rder: none;}.key{pos"
   "ition: absolute; hei"
   "ght: 48px; width: 10"
   "8px;}.key.up{top: 50"
   "px; left: 150px;}.ke"
   "y.down{top: 170px; l"
   "eft: 150px;}.key.lef"
   "t{top: 170px; left: "
   "0px;}.key.right{top:"
   " 170px; right: 0px;}"
   ".status{position: fi"
   "xed; top: 30px; righ"
   "t: 10px; font-size: "
   "20px; color: green;}"
   ".error{color: red;}i"
   "frame{height: calc(1"
   "00vh - 100px); width"
   ": calc(100vw - 20px)"
   "; border: 0;}</style"
   "></head><body> <h1>R"
   "obo Car Controller v"
   "2.0</h1> <iframe src"
   "=\"http://192.168.0."
   "112/picture/1/frame/"
   "\"></iframe> <div cl"
   "ass=\"status\"> </di"
   "v><div class=\"btn-w"
   "rp\"> <button type="
   "\"button\" class=\"b"
   "tn key up\" data-key"
   "=\"38\">&uarr;</butt"
   "on> <button type=\"b"
   "utton\" class=\"btn "
   "key left\" data-key="
   "\"37\">&larr;</butto"
   "n> <button type=\"bu"
   "tton\" class=\"btn k"
   "ey right\" data-key="
   "\"39\">&rarr;</butto"
   "n> <button type=\"bu"
   "tton\" class=\"btn k"
   "ey down\" data-key="
   "\"40\">&darr;</butto"
   "n> </div></body></ht"
   "ml>";